from dataclasses import dataclass, field
from typing import List, TextIO


@dataclass
class FileWriter:
    """This just forks output to multiple files. Knows nothing about Gcode"""


    # Where should we write the output
    filenames: List[str] = field(default_factory=list)
    files: List[TextIO] = field(default_factory=list, init=False)

    def __enter__(self):
        for filename in self.filenames:
            try:
                self.files.append(open(filename, "w"))
                print("yis")
            except FileNotFoundError as e:
                print(e)


        self.write_line("; Generated by Jeremy's Magical Octoflake Factory")
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        for open_file in self.files:
            try:
                open_file.close()
            except FileNotFoundError as e:
                print(e)


    def write_section_title(self, title):
        self.write_line(f"\n;;;;;;;; {title} ;;;;;;;;\n")

    def write_line(self, line, include_newline=True):
        for file in self.files:
            file.write(line + "\n" if include_newline else "")

    def write_lines(self, lines: List[str], include_newlines=True):
        for file in self.files:
            if include_newlines:
                file.writelines(line + "\n" for line in lines)
            else:
                file.writelines(lines)
