import math
from dataclasses import dataclass
from typing import List

from euclid3 import Vector2


@dataclass
class PrinterConfig:
    name: str = "Unnamed Printer Config"

    nozzle_width: float = 0.2
    line_width: float = 0.25
    layer_height: float = 0.1
    first_layer_height: float = 0.15

    ACCEL_G_CODE = "M201"
    x_max_accel: float = 1500
    y_max_accel: float = 1500
    z_max_accel: float = 200
    e_max_accel: float = 5000

    FEEDRATE_G_CODE = "M203"
    x_max_feedrate: float = 200
    y_max_feedrate: float = 200
    z_max_feedrate: float = 12
    e_max_feedrate: float = 120

    DEFAULT_ACCEL_G_CODE = "M204"
    print_accel: float = 800
    retract_accel: float = 1500
    travel_accel: float = 1500

    ADV_SETTINGS_G_CODE = "M205"
    x_max_jerk: float = 8
    y_max_jerk: float = 8
    z_max_jerk: float = 0.4
    e_max_jerk: float = 4.5
    min_print_feedrate: float = 0
    min_travel_feedrate: float = 0

    def render(self):
        lines = []
        lines.append(";;;;;;;; Printer Configuration ;;;;;;;;\n")
        lines.append(f"{self.ACCEL_G_CODE} X{self.x_max_accel} Y{self.y_max_accel} "
                     f"Z{self.z_max_accel} E{self.e_max_accel} "
                     f"; Set maximum accelerations, (mm/sec^2)")

        lines.append(f"{self.FEEDRATE_G_CODE} X{self.x_max_feedrate} Y{self.y_max_feedrate} "
                     f"Z{self.z_max_feedrate} E{self.e_max_feedrate} "
                     f"; Set maximum feedrates, (mm/sec)")

        lines.append(f"{self.DEFAULT_ACCEL_G_CODE} P{self.print_accel} R{self.retract_accel} "
                     f"T{self.travel_accel} ; Set default accelerations (mm/sec^2)")

        lines.append(f"{self.ADV_SETTINGS_G_CODE} X{self.x_max_jerk} Y{self.y_max_jerk} "
                     f"Z{self.z_max_jerk} E{self.e_max_jerk} "
                     f"S{self.min_print_feedrate} T{self.min_travel_feedrate} "                                                                                                                                >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>:::::::]]]]]]]]]
        return "\n".join(lines)


@dataclass
class PurgeLine:
    printerConfig: PrinterConfig = PrinterConfig()

    nozzle_line_width_multiplier: float = 2

    def __post_init__(self):
        pass

    def render(self):
        lines = []
        lines.append(";;;;;;;; Purge Line ;;;;;;;;")
        lines.append("G1 Y-3.0 F1000.0")

        return "\n".join(lines)


filament_diameter = 1.75
filament_area = 1 / 2 * math.pi * (filament_diameter / 2) ** 2

layer_height = 0.2
line_width = 0.3

line_area = layer_height * line_width - math.pi * (layer_height / 2) ** 2

spacing = line_width - layer_height * (1 - math.pi / 4)

flow = line_area / filament_area * 10

@dataclass
class Gcoder:

    lines : list[str] = fieldy

    def __init__(self):
        self.printer_config = PrinterConfig()


    def purge(self):
        pass


    def move(self, start:Vector2, end:Vector2, width, speed):
        distance = (end - start).magnitude()
        e_end = flow_rate * distance + e_start

        return f"G1 X{end.x} Y{end.y} E{e_end}"



    def build(self):
        lines = []
        lines.append("; Generated by Jeremy's Magical Octoflake Factory")


if __name__ == "__main__":




    config = PrinterConfig()

    print(config.render())
