import math

import euclid3

PREAMBLE = """


; generated by SuperSlicer 2.3.57 on 2022-02-23 at 00:06:44 UTC

; 

; external perimeters extrusion width = 0.25mm
; perimeters extrusion width = 0.40mm
; infill extrusion width = 0.40mm
; solid infill extrusion width = 0.40mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.40mm


M73 P0 R2
M73 Q0 S2
M201 X1000 Y1000 Z200 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm/sec
M204 P1250 R1250 T1500 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec

;TYPE:Custom
M862.3 P "MK3SMMU2S" ; printer model check
M862.1 P0.25 ; nozzle diameter check
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
Tx ; Load filament to extruder wheels, but not to nozzle
M190 S80 ; wait for bed temp
M109 S200 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
"""


PURGE = """


;go outside print area
G1 Y-3.0 F1000.0
G1 Z0.4 F1000.0
; select extruder
Tc ; load filament to nozzle 

; purge line
G1 X55.0 F2000.0
G1 Z0.3 F1000.0
G92 E0.0
G1 X240.0 E25.0 F1400.0
G1 Y-2.0 F1000.0
G1 X55.0 E25 F1400.0
G1 Z0.20 F1000.0
G1 X5.0 E4.0 F1000.0



; Don't change E value below. Excessive value can damage the printer.
M107
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K0.05 ; Filament gcode LA 1.5
M900 K30 ; Filament gcode LA 1.0
;LAYER_CHANGE
;Z:0.15
;HEIGHT:0.15
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.15


M73 P16 R2
M73 Q16 S2
G1 E-0.8 F2100
G1 Z0.15 F12000
G1 Z0.15
;AFTER_LAYER_CHANGE
;0.15
G1 Z0.3
M204 P1500
; G1 X108.203 Y88.984
M73 P17 R2
M73 Q17 S2
G1 Z0.15
G1 E0.8 F2100
;TYPE:Skirt
;WIDTH:0.4
G1 F1800


"""
#
# """
# G1 X107.697 Y89.716 E0.02041
# G1 X107.314 Y90.519 E0.02041
# G1 X107.064 Y91.373 E0.02041
# G1 X106.954 Y92.256 E0.02041
# G1 X106.95 Y117.635 E0.58213
# M73 Q18 S2
# G1 X107.106 Y118.815 E0.02732
# G1 X107.511 Y119.935 E0.02732
# G1 X108.149 Y120.948 E0.02745
# G1 X108.984 Y121.797 E0.02732
# """

END = """
; Filament-specific end gcode
G1 Z10.15 F720 ; Move print head up
M73 P97 R0
M73 Q97 S0
;G1 X0 Y210 F7200
M73 P98 R0
M73 Q98 S0
G1 E2 F5000
G1 E2 F5500
G1 E2 F6000
G1 E-15.0000 F5800
G1 E-20.0000 F5500
M73 P99 R0
M73 Q99 S0
G1 E10.0000 F3000
G1 E-10.0000 F3100
G1 E10.0000 F3150
G1 E-10.0000 F3250
G1 E10.0000 F3300

M140 S0 ; turn off heatbed
M107 ; turn off fan
M702 C
G4 ; wait
M221 S100 ; reset flow
M900 K0 ; reset LA

M104 S0 ; turn off temperature
M84 ; disable motors
M73 P100 R0
M73 Q100 S0"""



filament_diameter = 1.75
filament_area = 1/2 * math.pi * (filament_diameter/2) ** 2

layer_height = 0.2
line_width = 0.3

line_area = layer_height * line_width - math.pi * (layer_height/2)**2

spacing = line_width - layer_height * (1- math.pi/4)

flow = line_area / filament_area * 10

from euclid3 import  Vector2


def move(start:Vector2, end:Vector2, e_start=0, flow_rate = flow):

    distance = (end - start).magnitude()
    e_end = flow_rate * distance + e_start

    # ders







def make_square_spiral(x = 100, y= 100, n=10):

    r = 0
    out = []

    e = 0
    current = Vector2(x, y)
    next = Vector2(x, y)

    out.append(move(current, current, flow_rate=0))
    while r < n:
        # Assume we start at the bottom right

        r += 1
        next = current + Vector2(0, r)
        out.append(move(current, next))
        current = next



        next = current + Vector2(-r, 0)
        out.append(move(current, next))
        current = next

        r += 1

        next = current + Vector2(0, - r)
        out.append(move(current, next))
        current = next



        next = current + Vector2( r, 0)
        out.append(move(current, next))
        current = next

    return "\n".join(out)








def write_file(movements):
    with open("out/raw.gcode", "w") as f:
        f.write(PREAMBLE)
        f.write(PURGE)
        f.write(movements)
        f.write(END)

    # with open("raw.gcode", "r") as f:
    #     print(f.readlines())


if __name__=="__main__":



    # move(Vector2(0, 0), Vector2(1,1))
    # print(make_square_spiral(0, 0))
    moves = make_square_spiral(10, 10)
    print(moves)
    write_file(moves)
